### Получить всех сотрудников
GET http://localhost:8080/employees

### Создать сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Виктор",
  "lastName": "Михайлов",
  "department": 1,
  "salary": 1500

}

### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Андрей",
  "lastName": "Иванов",
  "department": 1,
  "salary": 3000

}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Григорий",
  "lastName": "Мишин",
  "department": 1,
  "salary": 5000

}

### Получить сумму зарплат по сотрудникам
GET http://localhost:8080/employees/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/high-salary

### Получить сотрудников по департаменту
GET http://localhost:8080/department/employees

### Получить сумму зарплат сотрудников по департаменту
GET http://localhost:8080/department/1/salary/sum

### Получить макс зарплату сотрудника по департаменту
GET http://localhost:8080/department/1/salary/max

### Получить мин зарплату сотрудника по департаменту
GET http://localhost:8080/department/1/salary/min

### Получить сотрудников сгрупированных по отделам
GET http://localhost:8080/department/1/employees
